# Generated by Django 6.0 on 2026-01-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('supply_route', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
            ],
        ),
    ]
