# Generated by Django 6.0 on 2026-01-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_group_name_remove_order_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(default='', help_text='Group name of the order', max_length=100),
        ),
    ]
